apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      name: payment-service-app
  template:
    metadata:
      labels:
        name: payment-service-app
    spec:
      containers:
      - name: application
        image: rendize/payment-service
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
          - name: DATABASE_URL
            valueFrom:
              configMapKeyRef:
                name: account-configmap
                key: DATABASE_URL
          - name: DATABASE_NAME
            valueFrom:
              configMapKeyRef:
                name: account-configmap
                key: DATABASE_NAME
          - name: SIGNING_KEY
            valueFrom:
              configMapKeyRef:
                name: account-configmap
                key: SIGNING_KEY
          - name: REDIS_URL
            valueFrom:
              configMapKeyRef:
                name: account-configmap
                key: REDIS_URL
          - name: PAYSTACK_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: dafe-secret
                key: PAYSTACK_SECRET_KEY
          - name: LEVEL_ONE_KEY
            valueFrom:
              secretKeyRef:
                name: dafe-secret
                key: LEVEL_ONE_KEY
          - name: LEVEL_TWO_KEY
            valueFrom:
              secretKeyRef:
                name: dafe-secret
                key: LEVEL_TWO_KEY
          - name: LEVEL_THREE_KEY
            valueFrom:
              secretKeyRef:
                name: dafe-secret
                key: LEVEL_THREE_KEY
          - name: LEVEL_ONE_IV
            valueFrom:
              secretKeyRef:
                name: dafe-secret
                key: LEVEL_ONE_IV
          - name: LEVEL_TWO_IV
            valueFrom:
              secretKeyRef:
                name: dafe-secret
                key: LEVEL_TWO_IV
          - name: LEVEL_THREE_IV
            valueFrom:
              secretKeyRef:
                name: dafe-secret
                key: LEVEL_THREE_IV
          - name: PAYMENT_ENCRYPTION_KEY
            valueFrom:
              secretKeyRef:
                name: dafe-secret
                key: PAYMENT_ENCRYPTION_KEY
          - name: PAYMENT_ENCRYPTION_IV
            valueFrom:
              secretKeyRef:
                name: dafe-secret
                key: PAYMENT_ENCRYPTION_IV
          - name: RAVE_SECKEY
            valueFrom:
              secretKeyRef:
                name: dafe-secret
                key: RAVE_SECKEY
          - name: FLUTTERWAVE_PUBLIC_KEY
            valueFrom:
              secretKeyRef:
                name: dafe-secret
                key: FLUTTERWAVE_PUBLIC_KEY
        volumeMounts:
        - name: account-configmap-volume
          mountPath: /etc/config
          readOnly: true
        - name: payment-secret-volume
          mountPath: "/etc/mafatih"
          readOnly: true
      volumes:
        - name: account-configmap-volume
          configMap:
            name: account-configmap
        - name: payment-secret-volume
          secret:
            secretName: dafe-secret
            
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  type: ClusterIP
  selector:
    name: payment-service-app
  ports:
  - port: 80
    targetPort: 3000
